### PR TITLE
Remove trailing space when currency is empty

### LINKED ISSUE #240: Trailing space when currency is empty
##### Reproduction steps

1. Go to settings
2. Set default currency to nothing/empty
3. Add a new transaction without currency

##### Expected behaviour
Transaction is saved to file without trailing space.

##### Actual behaviour
Transaction have extra space character after amount

##### System information
Latest version from F-Droid, 1.1.0

### PR DESCRIPTION
**Pull request by markokocic**
Fixes #240

### CODE REVIEW

File: app/src/main/java/be/chvp/nanoledger/ui/common/TransactionFormViewModel.kt [hunk 1]
```diff
@@ -174,6 +174,10 @@ abstract class TransactionFormViewModel
                     transaction.append(
                         "    ${account}${note}\n",
                     )
+                } else if (currency  == "") {
```
Comment (chvp) [inline app/src/main/java/be/chvp/nanoledger/ui/common/TransactionFormViewModel.kt:177]:
```suggestion
                } else if (currency == "") {
```

**Review by chvp — COMMENTED** [review]
This should fix the CI failure.

File: app/src/main/java/be/chvp/nanoledger/ui/common/TransactionFormViewModel.kt [hunk 2]
```diff
@@ -174,6 +174,10 @@ abstract class TransactionFormViewModel
                     transaction.append(
                         "    ${account}${note}\n",
                     )
+                } else if (currency == "") {
+                    transaction.append(
+                        "    $account  $spaces$quantity$note\n",
```
Comment (chvp) [inline app/src/main/java/be/chvp/nanoledger/ui/common/TransactionFormViewModel.kt:179]: To make sure the alignment is still correct:
```suggestion
                        "    $account  $spaces $quantity$note\n",
```

**Review by chvp — APPROVED** [review]
